# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:title.html
exclude:
  - Makefile
  - README.md
  - EXTRAS.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME

# Site info
url: "http://graphikamanila.com"
title: "Graphika Manila"

# Google analytics
analytics:
  hostname: "siteurl.com"
  id: "UA-XXXXXXXX-1"
